name: Python CI

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: flaskenvgithubactionswebapp/staging 
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  AZURE_SLOT_NAME: 'staging'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the exact version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Building web app
      uses: azure/appservice-build@v2  
    - name: Deploy Web App to staging slot
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}    
        slot-name: ${{ env.AZURE_SLOT_NAME }}     # The deployment slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 
